import Layout from '../components/layout'
import '../style/global.css'
import Head from 'next/head'
import { BlockTalkProvider } from "../Context/BlockTalkContext";

const MyApp = ({ Component, pageProps }) => (
    <div>

      <Head>
        <meta charset="utf-8" />
        <title>BlockTalk</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" type="image/png" href="./images/logo.png" />
      </Head>

      <BlockTalkProvider>
        <Layout>
          <Component {...pageProps} />
        </Layout>   
      </BlockTalkProvider>

    </div>
);

export default MyApp;
